version: '3.8'

services:
  data_preparation:
    build:
      context: .
      dockerfile: data_process/Dockerfile
    volumes:
      - ./data:/app/data  # Share data directory
    container_name: data_preparation_container

  training:
    build:
      context: .
      dockerfile: training/Dockerfile
    depends_on:
      - data_preparation  # Ensure data preparation runs first
    volumes:
      - ./data:/app/data  # Share data directory
      - ./models:/app/models  # Persist models
      - ./results:/app/results  # Persist results
    container_name: training_container

  inference:
    build:
      context: .
      dockerfile: inference/Dockerfile
    depends_on:
      - training  # Ensure training runs after training
    volumes:
      - ./data:/app/data  # Access data files
      - ./models:/app/models  # Access trained models
      - ./results:/app/results  # Persist inference results
    container_name: inference_container
