version: "3.8"

services:
  data_preparation:
    build:
      context: .
      dockerfile: ./data_process/Dockerfile
    command: python data_process/data_retreival.py
    volumes:
      - ./data:/app/data

  training:
    build:
      context: .
      dockerfile: ./training/Dockerfile
    command: python training/train.py
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    depends_on:
      - data_preparation

  inference:
    build:
      context: .
      dockerfile: ./inference/Dockerfile
    command: python inference/inference.py
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    depends_on:
      - training
